### ISSUE TITLE
Left click on taskbar icon for volumn not working on Windows 11

### ISSUE THREAD

**Issue by playgithub** [undergroundwires/privacy.sexy#102]
### Version
Windows 11 x64 21H2 22000.282
privacy.sexy 0.11.0

### Scripts
[privacy-script.zip](https://github.com/undergroundwires/privacy.sexy/files/7409937/privacy-script.zip)

### Question
Which patch causes the problem?

**Comment by ScribbleGhost** [comment]
Tried again today with a reboot after running the script. Same result. No problem.

There is no way to tell which part of the script is affects this problem, without a process of elimination which you are free to try yourself. I believe this has nothing to do with the script but without more information it's impossible to say.

**Comment by undergroundwires** [comment]
I can verify @ScribbleGhost , tested it on Windows 11 21H2 22000.194 and cannot reproduce, even after restart. It's probably something else that caused it 🤔

**Comment by playgithub** [comment]
BTW also installed Visual Studio 2019 Enterprise

**Comment by undergroundwires** [comment]
This may be related to another issue with taskbar #24. Maybe reverting `Microsoft AAD Broker Plugin app` may resolve it for you @playgithub . Feel free to let us know if it works or you already solved it another way.

**Comment by playgithub** [comment]
Linux now
I'll test it later
Thanks

**Comment by undergroundwires** [comment]
> Linux now I'll test it later Thanks

Same, switched to Linux as main OS, and it would be nice to have some privacy  scripts for Linux too. As you know your ideas are always welcome and appreciated, so feel free to add if you would like anything in [Linux discussion](https://github.com/undergroundwires/privacy.sexy/discussions/107).

**Comment by CaptainFrosty** [comment]
I don't know what's going on with the Quick Settings UI in Windows 11 but I don't think it has anything to do with these scripts. That thing has been randomly crashing and throwing all kinds of event log stuff since I upgraded. Debugger says it's the Shell Experience Host package which is where the Quick Settings dll is. I've had the AAD Broker Plugin installed. It throws errors too. Even since upgrading to Pro edition and resetting the errors persist. Doing a simple routine reset on Win11 Pro rather than 10 Home also destroyed my secure boot. I can't use it anymore. It boot looped immediately after the first restart following the cloud download, until I turned secure boot off. 

I thoroughly regret my upgrade to Windows 11. I like the UI more, but it isn't worth it. All these people I've seen on reddit and such saying, "oh it's just a UI makeover of Windows 10" clearly do not know what they are talking about. My experience says otherwise. 

I have a suspicion that some of these scripts are not safe for 11 despite it being the same version. For example disabling DoSvc seems to break Windows Store regardless of whether peer downloading is enabled or not. I broke it that way, fixed it, and now I've broken it again with something else. I'm just going to have to do a clean USB install straight from a Win11 image. That's the last thing I'm trying before I go back to 10.

**Comment by playgithub** [comment]
Recents news say that Win11 Dev Preview Build 22533 use a totally new volumn control popup window.
Closing it issue first, if I can reproduce it, I'll post it again with steps to reproduce it.

**Comment by playgithub** [comment]
Recents news say that Win11 Dev Preview Build 22533 use a totally new volumn control popup window.
Close it issue first, if I can reproduce it, I'll post it again with steps to reproduce it.

**Comment by playgithub** [comment]
> This may be related to another issue with taskbar #24. Maybe reverting `Microsoft AAD Broker Plugin app` may resolve it for you @playgithub . Feel free to let us know if it works or you already solved it another way.

Reverting `Microsoft AAD Broker Plugin app` doesn't help.

**Comment by hugoamvieira** [comment]
I used a modified strict script on a fresh install of W11 a few days ago and I'm having this same problem.
I also did not have access to the calendar when clicking on the date and time in the taskbar, however reverting "Windows Push Notification Service" under "Disable OS Services" has restored that.

Whenever I click on the Sound/Network icons in the taskbar, after a few seconds _something_ shows up for a few miliseconds then goes away. I noticed that right afterwards, an Event Viewer Application Error Log appears:
```
Faulting application name: ShellExperienceHost.exe, version: 10.0.22000.708, time stamp: 0x4e4cc679
Faulting module name: Windows.UI.QuickActions.dll, version: 10.0.22000.653, time stamp: 0xffd63ad9
Exception code: 0x80000003
Fault offset: 0x0000000000043381
Faulting process ID: 0x2368
Faulting application start time: 0x01d899411494a554
Faulting application path: C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe
Faulting module path: C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\Windows.UI.QuickActions.dll
Faulting package full name: Microsoft.Windows.ShellExperienceHost_10.0.22000.71_neutral_neutral_cw5n1h2txyewy
Faulting package-relative application ID: App
```

I also tried reverting the AAD Broker which did not help sadly.

This is a fresh install of W11 version 21H2 and I have not ran any other software that changes the default OS state other than this.

**Comment by playgithub** [comment]
@hugoamvieira
A recent test result several days ago:
* Standard script, no problem
* Uninstall Edge, problem
* 
I doubt that it depends on the base of edge.
