### ISSUE TITLE
[BUG]: Script not running correctly on windows 11 eduN

### ISSUE THREAD

**Issue by zany130** [undergroundwires/privacy.sexy#103]
### Description

The script is not running correctly 

### OS

Edition	Windows 11 Education N
Version	21H2
Installed on	‎10/‎31/‎2021
OS build	22000.282
Experience	Windows Feature Experience Pack 1000.22000.282.0

### Reproduction steps

    1. run provided script
    2. see errors
    3. reboot
    4. notice some apps like paint were not removed and Xbox apps were not installed

### Scripts

[privacy-script.txt](https://github.com/undergroundwires/privacy.sexy/files/7449833/privacy-script.txt)

### Additional information

errors:
[privacysexy.txt](https://github.com/undergroundwires/privacy.sexy/files/7449835/privacysexy.txt)

**Comment by celphogeek** [comment]
Did you unblock the file? when you download .bat, .cmd or any files they have a little protection from windows that you need to right-click>Properties>And them click unblock.
After that try run the script again

**Comment by celphogeek** [comment]
I check the file to see the errors and all of them is normal, since you don't have the xbox app or any other apps, you will see errors. For example, the scripts selected you choose revert, but the script just use a normal method to revert the app, but don't verify for dependencies for the apps, so, if you don't have the script will try to proceed and you might find some errors.

the services and registry errors, some registry key was not found and the services shows the error because can't start the service and try to re-enable or configure to the state you want. But, most of time you need to restart the computer to take effect.

**Comment by celphogeek** [comment]
And the command to revert the Apps, will only work if you remove the package for the current user not for all users, since the command try to use the AppxManifest.xml

**Comment by zany130** [comment]
oh ok so I was wrong in assuming that this script would install the media features missing in the N version along with all the xbox apps? also I did notice I was disabling a few things that are needed for microsoft sign in (which I would need for the xbox apps) after fixing that I was able to add the media feature through the app and features setting page and install the xbox apps from the store
[fixXbox.txt](https://github.com/undergroundwires/privacy.sexy/files/7450413/fixXbox.txt)
d
