### ISSUE TITLE
Windows LTSC support

### ISSUE THREAD

**Issue by ThiagoRangel7** [undergroundwires/privacy.sexy#113]
Windows LTSC versions are already pretty debloated out of the box, and due to that lots of the scripts don't apply well. It doesn't come with Cortana, for example, therefore most of the Cortana disabling scripts render useless and end up only bloating the registry with keys that didn't even exist in the first place.

For example: "Do not allow Cortana" script makes changes to **Key:** HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search **Value:** AllowCortana, but that entire "Windows Search" key doesn't even exist in LTSC.
Cortana is just an example, there are a lot of others.

I don't know for sure if allowing the script to create these keys (even if the values are set to "disabled") could cause any problems, but I think this is "making it worse" instead of better, because it's only polluting the registry.

I suggest that either:

1. The script firstly tries to detect if the keys actually exist before creating them only to disable it right after, or
2. That we could choose "Windows LTSC" as a separate platform (just like we can choose MacOS and Linux), then the available scripts would be different than normal Windows.

**Comment by bardiarajabi** [comment]
@ThiagoRangel7 Which LTSC version do you mean?
for ex. on old ltsc version(s) like 1607 cortana is ripped with windows search.Its normal.

**Comment by undergroundwires** [comment]
Hi @ThiagoRangel7, thank for your constructive feedback.

Pros: You harden your configurations against potential future installations. Cons: You store a few KBs of data. For me the pros weigh out the cons. You may not prefer this which I see.

1. This would work fine if the keys always exist, but even in non LTSC versions keys do not necessarily exist. You can search for `reg delete` in [collection file](https://github.com/undergroundwires/privacy.sexy/blob/0.11.3/src/application/collections/windows.yaml) and you will see that many scripts deletes registry key instead of changing its value because by default these keys do not exist.

2. I don't think that community would be willing to tag every script based on whether they are needed in every LTSC version, and then maintain this list. And I would not want to spend my time into testing those instead of prioritizing fixing bugs or doing improvements.
