### ISSUE TITLE
Block telemetry.dropbox.com

### ISSUE THREAD

**Issue by chr15t0ph** [undergroundwires/privacy.sexy#118]
Dear privacy.sexy,

could you please add blocking of telemetry.dropbox.com in your script base?

Kind regards
Christoph

**Comment by undergroundwires** [comment]
Hi @chr15t0ph ,

This will eventually be implemented along with support for blocking other URLs in hosts files and other network security improvements. We can expect optimistically end of this year, but can be later. I prioritize stability over new functions as it's not fun stuff stops working on your computer.

FYI: This has been a long-term target. I've been taking small steps towards this goal when I was building a [templating language](https://github.com/undergroundwires/privacy.sexy/blob/0.11.3/docs/templating.md) so we can do something like `for each url -> block url`. This would allow massblocking list of URLs without repeating code.

If you send a small PR only for short time fix for URL, I will merge it. You can read more in [extending scripts](https://github.com/undergroundwires/privacy.sexy/blob/master/CONTRIBUTING.md#extend-scripts).

**Comment by Abyssgrowth** [comment]
> Dear privacy.sexy,
> 
> could you please add blocking of telemetry.dropbox.com in your script base?
> 
> Kind regards Christoph

pretty sure https://safing.io portmaster already blocks this by default.

**Comment by femdiya** [comment]
Just a quick info, hosts file may not be enough for blocking the ENTIRE website, for example:
dropbox.com only block this domain:
it doesn't block telemetry.dropbox.com
it doesn't block www.dropbox.com
it doesn't block randomly generated sub-domains like irjfnjfjjffktelementry.dropbox.com.
Please refer to https://oisd.nl/faq#legacysyntaxes for more information.
@undergroundwires

**Comment by undergroundwires** [comment]
Yes, blocking URLs through hosts file has limitations. However, the goal was to block telemetry URLs not everything under dropbox.com and telemetry URLs are often specific, so hosts file works fine for most cases. We do not have any other option either, Windows Firewall works with IP only not FQDN. I'm interested to know if there is any other option though.

Closing this since hosts blocking along with Dropbox is added since [0.13.0](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.0) 🚀.
