### ISSUE TITLE
[BUG]: Script CHANGED ALL DEFAULT SETTINGS

### ISSUE THREAD

**Issue by SonaliBendre** [undergroundwires/privacy.sexy#121]
here is the script - https://bin.piracy.moe/?9482ebf863cbc8e2#HGCFWi9mQiwBN5WG6dgfmj5aowsrsr3XDpRd3fMrQV8n

can you please give reverse script?

**Comment by bardiarajabi** [comment]
**_Deny app access to account info, name, and picture_**
it caused many problems for my micro$oft account

**_Disable Windows DRM internet access_**
Maybe Your apps are using DRM?

**_Deny app access to microphone
Deny app access to radios
Deny app access to bluetooth devices
Deny app access to Document folder
Deny app access to Pictures folder
Deny app access to Videos folder
Deny app access to other filesystem
Deny app access to camera
Deny app sync with devices (unpaired, beacons, TVs, etc.)
Deny app access to trusted devices_**
These can perform a lot of issues on apps

**_Deny app access to Notifications_**
Notifications btw.

Here is the revert script
[privacy-script.zip](https://github.com/undergroundwires/privacy.sexy/files/8066263/privacy-script.zip)

**Comment by SonaliBendre** [comment]
@bardiarajabi thank you awesome

**Comment by bardiarajabi** [comment]
@SonaliBendre No problem <3

**Comment by undergroundwires** [comment]
@bardiarajabi I see that some of these are not recommended at all, but most of them are "standard" to all users. Maybe this is too much then? Would you recommend to move them to "strict"?

**Comment by bardiarajabi** [comment]
@undergroundwires
![fr2kjp8fa4h21](https://user-images.githubusercontent.com/69072090/156934253-373665f9-6fa1-4b02-b1ee-ee80c205ca43.jpg)
I use strict settings on my gaming-only machine.
I would not recommend these settings to anyone.
P.S.: I use disable windows update to fix my dad's pc. IDK if it's that strict or not.

**Comment by undergroundwires** [comment]
[0.13.4](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.4) is just released 🎉. It improves app disabling to resolve this issue, some of the improvements include:

- It adds caution text for all scripts about potential impacts.
- Move disabling app access to notifications from 'Standard' to 'Strict'.
- Move disabling app access to phone calls from 'Standard' to 'Strict'.
- Add more documentation to scripts
- Improve code comments for better clarity on generated outputs.
- Resolve error display in revert codes due to incorrect use of `reg  delete` commands.
- Fix disabling app access to trusted devices disables access to account information, name and picture on older versions of Windows.
- Rename script names for consistency and clarity.

Please create new issues for further ideas/problems.
