### ISSUE TITLE
[BUG/PROBLEM]: No Mapping between account names and Security Id was done

### ISSUE THREAD

**Issue by adnage19** [undergroundwires/privacy.sexy#129]
### Description

I'm getting **No Mapping between account names and Security Id was done** (_Nie zostało wykonane mapowanie między nazwami kont a identyfikatorami zabezpieczeń_ in Polish language in the log) problem in some point of script execution. Here is an example how it looks in the log:

> SUCCESS: The file (or folder): "C:\Program Files\Windows Defender Advanced Threat Protection\MsSense.exe" now owned by user "Dell\Gosia".
> administrators: Nie zostało wykonane mapowanie między nazwami kont a identyfikatorami zabezpieczeń.
> Successfully processed 0 files; Failed processing 1 files
> Odmowa dostępu.
>         0 file(s) moved.
> Could not move C:\Program Files\Windows Defender Advanced Threat Protection\MsSense.exe

Or:

> --- Lock app (shows lock screen)
> administrators: Nie zostało wykonane mapowanie między nazwami kont a identyfikatorami zabezpieczeń.
> Failed to take ownership
> At line:1 char:501
> + ... > nul'); if($LASTEXITCODE) { throw 'Failed to take ownership' }; $fil ...
> +                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (Failed to take ownership:String) [], RuntimeException
>     + FullyQualifiedErrorId : Failed to take ownership
> 

The script was executed on freshly installed Windows 11 Pro with local account - I haven't changed anything in account settings - I just created account during Windows setup and that's all. I have tried to Google this problem but I haven't found anything helpful.  I know it doesn't have to be script problem itself but any kind of help would be appreciated
### OS

Windows 11 Pro 22000.527

### Scripts

[log.txt](https://github.com/undergroundwires/privacy.sexy/files/8187783/log.txt)

**Comment by undergroundwires** [comment]
Thanks for such a nice bug report @adnage19 .

I tried both failed to reproduce both in Windows 11 21H2 in English version.

The command failing for you is `icacls`. You cannot take ownership of the files. These files are not owned by regular user/administrator as a security mechanism to prevent access. However, we give their ownership to "Administrator" group so we can move them around (backup and get rid of from original location).

I guess this is caused by Polish version of Windows not having hardcoded "Administrator" group. But something else.

Can you open `cmd` terminal and run:

```batchfile
PowerShell -ExecutionPolicy Unrestricted -Command "$sid = [System.Security.Principal.SecurityIdentifier]::new('S-1-5-32-544'); $name = $sid.Translate([System.Security.Principal.NTAccount]); echo $name"
```

And share what it outputs for you. It would validate whether this is caused by this translation I'm guessing.

**Comment by undergroundwires** [comment]
Thanks for such a nice bug report @adnage19 .

I failed to reproduce both in Windows 11 21H2 in English version.

The command failing for you is `icacls`. You cannot take ownership of the files. These files are not owned by regular user/administrator as a security mechanism to prevent access. However, we give their ownership to "Administrator" group so we can move them around (backup and get rid of from original location).

I guess this is caused by Polish version of Windows not having hardcoded "Administrator" group. But something else.

Can you open `cmd` terminal and run:

```batchfile
PowerShell -ExecutionPolicy Unrestricted -Command "$sid = [System.Security.Principal.SecurityIdentifier]::new('S-1-5-32-544'); $name = $sid.Translate([System.Security.Principal.NTAccount]); echo $name"
```

And share what it outputs for you. It would validate whether this is caused by this translation I'm guessing.

**Comment by adnage19** [comment]
Thank you for the reply. You can be right, because I'm getting this value: 

> Value
> -----
> BUILTIN\Administratorzy

_Administratorzy_ is Polish plurar of _Administrator_
Should I try to change language to English?

**Comment by adnage19** [comment]
Bingo! I have manually changed the group name and it worked. Now other small bug appeared - despite removing Windows Security GUI app, the app is still visible in All apps list.

**Comment by undergroundwires** [comment]
Thank you for you quick feedback @adnage19 . I'll fix this and release a patch in 1-2 days. "BUILTIN/Administrator" is hardcoded and expected which works in many languages but somehow Polish group seems to be different. I will change this to not be hardcoded anymore that will fix your issue.

Could you create another bug report for the remaining shortcut using the template? A screenshot would be great so we can take it from there.

**Comment by undergroundwires** [comment]
Thank you for you quick feedback @adnage19 . I'll fix this and release a patch in 1-2 days. "Administrator" is hardcoded and "BUILTIN/Administrators" was expected which works in many languages but somehow Polish group seems to be different. I think changing "system" language and UI language are different things in UI and you could change system language to English. But this is a problem from privacy.sexy side and I will change this to not be hardcoded anymore that will fix your issue and work with any value.

Could you create another bug report for the remaining shortcut using the template? A screenshot would be great so we can take it from there.

**Comment by undergroundwires** [comment]
This has been fixed for a while now, closing the issue.
