### ISSUE TITLE
[Improvement] Fix broken functionality from Edge Removal. Move Uninstall Edge -> Standard

### ISSUE THREAD

**Issue by rcmaehl** [undergroundwires/privacy.sexy#156]
### OS

Windows

### Name

Fix Broken Functionality From Edge Removal

### Script code

https://github.com/AveYo/fox/blob/main/Edge_Removal.bat#L79

### Revert code

https://github.com/AveYo/fox/blob/main/Edge_Removal.bat#L98

### Suggested category

Remove Bloatware

### Suggested recommendation level

STANDARD

### Additional documentation/references

Most edge removal scripts break search functionality among other features. Aveyo has created a script that fixes this functionality and allows it to be redirected to the default web browser.

**Comment by undergroundwires** [comment]
Thank you for the reference and suggestion. 

1. Edge removal in privacy.sexy does not break any functionality including search. Not according to my tests, not according to community reports. It should be completely safe to run, please create a bug report otherwise and we can address directly.
2. Removing Edge on standard my have shock affect on people. Grandmothers run standard blindly with trust that it would not break anything for them. If they had a loot of bookmarks and uses Edge as daily driver, it would frustrate them completely for them.
3. With all respect to author who help the community, I cannot accept this script as it is. It is too dirty and complex at a level that obfuscates what's going on. It cannot accept this and find it unmaintainable. If we want to have it in privacy.sexy, it needs to be re-written in a clean and simpler way and extend existing functionality.
