### ISSUE TITLE
Compare files option

### ISSUE THREAD

**Issue by VOO3f5QrpWgQn** [undergroundwires/privacy.sexy#283]
The ability to import existing scripts, in which the set settings are then automatically loaded, would greatly simplify the work after version updates.
Currently, a completely new script has to be created and the changes then have to be compared manually.

**Comment by undergroundwires** [comment]
Thank you for the request. This will eventually be implemented. Stability is higher prioritized than new feature, even though this sounds boring I guess we all appreciate a software that does what it intents to do in a robust way more. I will do this when I can have time rather than fixing existing stuff. Let's keep single issue #59 to track the progress.
