### ISSUE TITLE
[BUG]: An error in script generation

### ISSUE THREAD

**Issue by sgimsrs5555** [undergroundwires/privacy.sexy#291]
The script generation fails when these particular elements are selected
Disable Defender features
Disable OS components for Defender

Thanks for the great work!

**Comment by undergroundwires** [comment]
Hi, thank you for the nice comment. Is this same as #264? It's on my TODO list. A proper solution would be executing the scripts from memory instead of writing to file first to avoid interference from Defender, but this sounds like building some kind of malware, and I do not really want to that road. I think building an informative dialog would be fine, so the users can manually execute the script. What do you think?
