### ISSUE TITLE
Recent Windows 11 Security Update marks "privacy-script" as Virus or unwanted Software [BUG]: 

### ISSUE THREAD

**Issue by laurenz0071** [undergroundwires/privacy.sexy#296]
### Description

Recent Windows 11 Security Update marks "privacy-script" as Virus or unwanted Software. Then the scriped can't be executed and gets deleted by Windows.

### OS

Windows 11, 2023-12 Cumulative Update for Windows 11 Version 22H2 for arm64-based Systems (KB5033375),
Security Intelligence-Update for Microsoft Defender Antivirus - KB2267602 (Version 1.403.529.0)
Running on Macbook Air 15 2023 via Parallel Desktop 18

### Reproduction steps

    1. Go to 'https://privacy.sexy/'
    2. Download 'lates Script Windows'
    3. Click on 'privacy-script' to execute under admin privileges
    4. It's not executed but deleted. 
    5. It is also not possible to execute the file directly via the privacy.sexy offline version.

**Comment by undergroundwires** [comment]
Hi @laurenz0071,
I see that Microsoft Defender team has actually declared against privacy.sexy and adds signatures of privacy.sexy scripts specifically, so we got some attention.
Is this only disabling defender script or do you get this with "Standard" or "Strict" modes too?

**Comment by undergroundwires** [comment]
Hi @laurenz0071,

Thank you for bringing this to our attention. I can reproduce that recent updates to Defender on Windows 10 and 11 are mistakenly flagging our scripts as harmful. Rest assured, this is a false positive; privacy.sexy is designed to enhance user privacy and security, and it's used widely across various sectors, including military agencies.

Security is top priority at privacy.sexy and we welcome any security audits of our open-source code. Commitment to security is detailed in [SECURITY.md](https://github.com/undergroundwires/privacy.sexy/blob/master/SECURITY.md). We believe in **transparency** and the **right to privacy**, and we encourage security researchers including Defender team to review our code and create issues if there are real issues so we can address them.

Microsoft Defender team has actually declared war against privacy.sexy and adds signatures specifically targeting privacy.sexy. It affects even **Standard** selection which is the least aggressive option, doing nothing more than increasing your security. The reason is that we're target specifically is because the tool is minimizing surveillance and giving options  the **right way**, meanwhile other more popular tools that are pretty-much placebo/snake oil stay on the market.

This is **serious** and in a legal challenge, this would be a clear win on privacy.sexy:

- Microsoft are preventing users from willingly choose software they'd like to use. which raises concerns about user autonomy.
- Microsoft's dominant market status and this enforcement favors  data collection practices, leading to a monopolistic and aggressive position.

To address this:

- **Web version: ** Add notification about this false positive and provide guidance on how to safely download and use the desktop version. Users can also manually add an exclusion in Defender or run the scripts by copy/pasting. Other options such as distributing `.exe` files, but this requires more underlying infrastructure therefore money.
- **Desktop version**: There can be various fixes and will start by updating the UI with an error message. We are open to suggestions and welcome community input.

We invite you to:

- Share your experience and opinions on social platforms to make our voice heard.
- To keep the project sustainable and functional, consider donating here: [Donate to privacy.sexy](https://undergroundwires.dev/donate?project=privacy.sexy).

**Comment by undergroundwires** [comment]
Hi @laurenz0071,

Thank you for bringing this to our attention. I can reproduce that recent updates to Defender on Windows 10 and 11 are mistakenly flagging our scripts as virus. Rest assured, this is a false positive; privacy.sexy is designed to enhance user privacy and security, and it's used widely across various sectors, including military agencies.

Security is top priority at privacy.sexy and we welcome any security audits of our open-source code. Commitment to security is detailed in [SECURITY.md](https://github.com/undergroundwires/privacy.sexy/blob/master/SECURITY.md). We believe in **transparency** and the **right to privacy**, and we encourage security researchers including Defender team to review our code and create issues if there are real issues so we can address them.

Microsoft Defender team has actually declared war against privacy.sexy and adds signatures specifically targeting privacy.sexy. It affects even **Standard** selection which is the least aggressive option, doing nothing more than increasing your security. We're being targeted specifically because the tool is minimizing surveillance and giving options the **right way**, meanwhile other more popular but mostly useless tools that are placebo/snake oil stay on the market.

This is **serious** and in a legal challenge, this would be a clear win for privacy.sexy:

- Microsoft's actions in preventing users from choosing their preferred software could raise concerns regarding user consent and choice.
- The use of Microsoft's dominant market position to enforce certain data collection practices could be seen as problematic from a competition standpoint.

To address this:

- **Web version:** Add notification about this false positive and provide guidance on how to safely download and use the desktop version. Users can also manually add an exclusion in Defender or run the scripts by copy/pasting. Other options such as distributing `.exe` files requires more underlying infrastructure and increase costs.
- **Desktop version**: There can be various fixes and will start by updating the UI with an error message. We are open to suggestions and welcome community input.

We invite you to:

- Share your experience and opinions on social platforms to make our voice heard.
- To keep the project sustainable and functional, consider donating here: [Donate to privacy.sexy](https://undergroundwires.dev/donate?project=privacy.sexy).

**Comment by undergroundwires** [comment]
Hi @laurenz0071,

Thank you for bringing this to our attention. I can reproduce that recent updates to Defender on Windows 10 and 11 are mistakenly flagging our scripts as virus. Rest assured, this is a false positive; privacy.sexy is designed to enhance user privacy and security, and it's used widely across various sectors, including military agencies.

Security is top priority at privacy.sexy and we welcome any security audits of our open-source code. Commitment to security is detailed in [SECURITY.md](https://github.com/undergroundwires/privacy.sexy/blob/master/SECURITY.md). We believe in **transparency** and the **right to privacy**, and we encourage security researchers including Defender team to review our code and create issues if there are real issues so we can address them.

Microsoft Defender team has actually declared war against privacy.sexy by adding signatures specifically targeting privacy.sexy. It affects even **Standard** selection which is the least aggressive option, doing nothing more than increasing your security. We're being targeted specifically because the tool is minimizing surveillance and giving options the **right way**, meanwhile other more popular but mostly useless tools that are placebo/snake oil stay on the market.

This is **serious** and in a legal challenge, this would be a clear win for privacy.sexy:

- Microsoft's actions in preventing users from choosing their preferred software could raise concerns regarding user consent and choice.
- The use of Microsoft's dominant market position to enforce certain data collection practices could be seen as problematic from a competition standpoint.

To address this:

- **Web version:** Add notification about this false positive and provide guidance on how to safely download and use the desktop version. Users can also manually add an exclusion in Defender or run the scripts by copy/pasting. Other options such as distributing `.exe` files requires more underlying infrastructure and increase costs.
- **Desktop version**: There can be various fixes and will start by updating the UI with an error message. We are open to suggestions and welcome community input.

We invite you to:

- Share your experience and opinions on social platforms to make our voice heard.
- To keep the project sustainable and functional, consider donating here: [Donate to privacy.sexy](https://undergroundwires.dev/donate?project=privacy.sexy).

**Comment by undergroundwires** [comment]
Hi @laurenz0071,

Thank you for bringing this to our attention. I can reproduce that recent updates to Defender on Windows 10 and 11 are mistakenly flagging our scripts as virus. Rest assured, this is a false positive; privacy.sexy is designed to enhance user privacy and security, and it's used widely across various sectors, including military agencies.

Security is top priority at privacy.sexy and we welcome any security audits of our open-source code. Commitment to security is detailed in [SECURITY.md](https://github.com/undergroundwires/privacy.sexy/blob/master/SECURITY.md). We believe in **transparency** and the **right to privacy**, and we encourage security researchers including Defender team to review our code and create issues if there are real issues so we can address them.

Microsoft Defender team has actually declared war against privacy.sexy by adding signatures specifically targeting privacy.sexy. It affects even **Standard** selection which is the least aggressive option, doing nothing more than increasing your security. We're being targeted specifically because the tool is minimizing surveillance and giving options the **right way**, meanwhile other more popular but mostly useless tools that are placebo/snake oil stay on the market.

This is **serious** and in a legal challenge, this would be a clear win for privacy.sexy:

- Microsoft's actions in preventing users from choosing their preferred software could raise concerns regarding user consent and choice.
- The use of Microsoft's dominant market position to enforce certain data collection practices could be seen as problematic from a competition standpoint.

To address this:

- **Web version:** Add notification about this false positive and provide guidance on how to safely download and use the desktop version. Users can also manually add an exclusion in Defender or run the scripts by copy/pasting. Other options such as distributing `.exe` files require more underlying infrastructure and increase costs.
- **Desktop version**: There can be various fixes and will start by updating the UI with an error message. We are open to suggestions and welcome community input.

We invite you to:

- Share your experience and opinions on social platforms to make our voice heard.
- To keep the project sustainable and functional, consider donating here: [Donate to privacy.sexy](https://undergroundwires.dev/donate?project=privacy.sexy).

**Comment by laurenz0071** [comment]
Thank you for the fast feedback. I was able to add a Security Defender exception and can now execute the script as usual.

**Comment by undergroundwires** [comment]
Adding this on the web UI:

![image](https://github.com/undergroundwires/privacy.sexy/assets/15555035/43f63ff1-3709-4642-ae09-00c91dc56aef)

**Comment by undergroundwires** [comment]
Good news 🎉. Microsoft has removed the aggressive signatures, `Standard` collection does no longer trigger antivirus alerts on after Defender signature update. Thank you for the cooperation Defender team ❤️!

Closing this due to:

- Web application show now instructions on how to save the file even if antivirus alerts.
- Desktop application now shows error if it detects antivirus intervention.
- Microsoft has removed the aggressive signatures, `Standard` is no longer triggering antivirus alert.

A follow-up issue would be to automate disabling antivirus.
