### ISSUE TITLE
Can't open start menu

### ISSUE THREAD

**Issue by nordkurre** [undergroundwires/privacy.sexy#316]
So i did a fresh install of windows 11 and decided to use this program to upgrade my privacy and security. I selected the tweaks i wanted and started the script. Everything was fine until the script was about halfway done and i noticed that i no longer could launch the start menu.

 I searched the web and tried to in powershell write "Get-AppxPackage -AllUsers Microsoft.Windows.ShellExperienceHost | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}" to re-register the start menu but it still wouldn't open. I searched thru all the scripts but none of them mentioned disabling the start menu. 

Have i missed something? Which script disables the start menu?

**Comment by undergroundwires** [comment]
Hi please attach the generated privacy.sexy file, on desktop version you can find it at `%APPDATA%\privacy.sexy\runs`.

**Comment by marcello-pietrobon** [comment]
I remember when using Blackbird (they are not updating it since November 22 if I do not err) I have a similar problem and I wrote a note for myself.

`StartMenuExperienceHost`: disabling it will make the start menu disappear, but the search box still there. With Blackbird this change was irreversible.

`ShellExperienceHost`: disabling it will disable the Time/Clock panel on the System Tray. With Blackbird this change was reversible.

**Comment by nordkurre** [comment]
[privacy-script.zip](https://github.com/undergroundwires/privacy.sexy/files/14169092/privacy-script.zip)

Made it a zip because github wouldn't let me post it otherwise

**Comment by undergroundwires** [comment]
I cannot reproduce this. Start menu works fine after running the script in Windows 11 23H2, even after restarting explorer or the computer.

Thank you for the information about the apps. `ShellExperienceHost` is already excluded from privacy.sexy and thank you for the information about `StartMenuExperienceHost`, it will never be added.
