### ISSUE TITLE
[BUG]: Ran the standard protection and now my Windows does not display notifications to apps like Instagram and Whatsapp

### ISSUE THREAD

**Issue by hollowflowers** [undergroundwires/privacy.sexy#339]
I ran the script a week ago, since then I noticed my Windows does not display notifications to nothing.
I really mean nothing, not even Windows Defender alarms.
Is there any way I can fix it?
Also when I mess around in Settings app, I get a lot of the [System Error:An Overrun of a stack-based buffer in windows] error.

**Comment by plantindesk** [comment]
![image](https://github.com/undergroundwires/privacy.sexy/assets/101469826/196c1f67-f7c5-4bc7-8135-2d6c0dd6de66)

Did you checked this?

**Comment by hollowflowers** [comment]
I probably got this on, but I didnt check it myself.
I´ll try to revert it to see
Thank you friend.

**Comment by undergroundwires** [comment]
Hi @hollowflowers, did @plantindesk's suggestion  this resolve your issue?

**Comment by hollowflowers** [comment]
no, I reinstalled Windows. but I´m pretty sure I used some setting that broke it or uninstalled some sort of framework, idk.
________________________________
De: undergroundwires ***@***.***>
Enviado: sábado, 27 de abril de 2024 11:49
Para: undergroundwires/privacy.sexy ***@***.***>
Cc: hollowflowers ***@***.***>; Mention ***@***.***>
Assunto: Re: [undergroundwires/privacy.sexy] [BUG]: Ran the standard protection and now my Windows does not display notifications to apps like Instagram and Whatsapp (Issue #339)


Hi @hollowflowers<https://github.com/hollowflowers>, did @plantindesk<https://github.com/plantindesk>'s suggestion this resolve your issue?

**Comment by undergroundwires** [comment]
[0.13.4](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.4) is just released 🎉. It improves app disabling to resolve this issue, some of the improvements include:

- It adds caution text for all scripts about potential impacts.
- Move disabling app access to notifications from 'Standard' to 'Strict'.
- Move disabling app access to phone calls from 'Standard' to 'Strict'.
- Add more documentation to scripts
- Improve code comments for better clarity on generated outputs.
- Resolve error display in revert codes due to incorrect use of `reg  delete` commands.
- Fix disabling app access to trusted devices disables access to account information, name and picture on older versions of Windows.
- Rename script names for consistency and clarity.

Please create new issues for further ideas/problems.
