### ISSUE TITLE
Apple silicon processor support

### ISSUE THREAD

**Issue by AlexanderDankin** [undergroundwires/privacy.sexy#348]
I really wish there was support for “M” series processors.

**Comment by undergroundwires** [comment]
Hi @AlexanderDankin,

I guess you mean the desktop application. It works fine on M processors for me. What issue did you have?

**Comment by AlexanderDankin** [comment]
There are no problems as such, except for the application taking too long to start up. 
I can only speculate, but maybe it's because the application is optimized for 
intel processors.

**Comment by plantindesk** [comment]
> There are no problems as such, except for the application taking too long to start up. I can only speculate, but maybe it's because the application is optimized for intel processors.

The app is build using ElectronJS which is a framework that utilize web technologies and therefore are not native in the traditional sense. So it lacks performance

**Comment by undergroundwires** [comment]
The binary for macOS is x64, but this gets emulated on Apple that has performance impact:

> Native apps run more efficiently than translated apps because the compiler is able to optimize your code for the target architecture. An app that supports only the x86_64 architecture must run under Rosetta translation on Apple silicon
> [Apple Documentation](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary%23overview)

🚀 I just added System Requirements docs to clarify this: [system-requirements.md](https://github.com/undergroundwires/privacy.sexy/blob/c580742a886b9645309703de2493a1b14282ac17/docs/desktop/system-requirements.md).

---

**Solution suggestion 1: Universal packages**

So changing macOS releases to universal packages may help with the issue. This seems to be basically packaging ARM and x64 versions together in same file.

@plantindesk is right. Here is the [electron-builder configuration](https://github.com/undergroundwires/privacy.sexy/blob/0.13.0/electron-builder.cjs). Luckily electron-builder supports universal packages:

- Main issue: electron-userland/electron-builder#5475
- Configuration examples with targeting both `x64` and `arm64`: electron-userland/electron-builder#5689, electron-userland/electron-builder#5426
- There seems to be `universal` option which makes it even better: electron-userland/electron-builder#5481

---

**Solution suggestion 2: Do not show the white blank page**

Another think we can do is to avoid showing white blank page while application is loading, see [this blog post](https://www.christianengvall.se/electron-white-screen-app-startup/#ready-to-show-event) or [this](https://dev.to/vadimdemedes/making-electron-apps-feel-native-on-mac-52e8#first-render) for visual examples.

---

What do you think?

**Comment by plantindesk** [comment]
I think building both arm64 and x64 build for MacOS

**Comment by undergroundwires** [comment]
How about hiding the window until HTML/CSS/JS is loaded? I guess this should not be only macOS only but also be part of Windows/Linux versions. Do you see any side-effect having this on Windows/Linux?

I demonstrate this on Linux:

| Now (with initial blank page) | After (window hidden until loaded) |
| --------------------------------- | ----------------------------------------- |
| ![with-flash](https://github.com/undergroundwires/privacy.sexy/assets/15555035/eaa0c467-4c4b-43e3-a064-e22c0523daa7) | ![without-flash](https://github.com/undergroundwires/privacy.sexy/assets/15555035/8cf5a861-f1f8-4ae9-bca7-e8e2e44375d7) |

**Comment by plantindesk** [comment]
Thats best idea

**Comment by plantindesk** [comment]
Off topic: Also you use Ubuntu :-/

**Comment by undergroundwires** [comment]
So hiding window until loaded is released as part of [0.13.3](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.3) 🎉

The packaged application is now arm64 (Apple Silicon) native. So it should run smoth now, feel free to verify this with 0.13.3 @AlexanderDankin.

It’s weird because I have never configured this arm64 build 😅. I guess this is because macOS GitHub runner (CI/CD) agents have been updated automatically to be ARM-based, and this resulted in ARM-only builds. I verify this by running `file /Applications/privacy.sexy.app/Contents/MacOS/privacy.sexy` command, which gives me:  

```
/Applications/privacy.sexy.app/Contents/MacOS/privacy.sexy: Mach-O 64-bit executable arm64
```

This will break desktop application on all other Intel-based macs 🤦. So I will migrate to universal builds for macOS in 0.13.4.

I will also update [desktop execution tests](https://github.com/undergroundwires/privacy.sexy/blob/0.13.3/.github/workflows/checks.desktop-runtime-errors.yaml) (which actually installs the software and ensures it runs OK), to run on both Intel and ARM-based macs to verify that it runs fine on both platforms.

**Comment by AlexanderDankin** [comment]
Thank you! Indeed the app started to open much faster.

**Comment by undergroundwires** [comment]
[0.13.4](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.4) is just released  🎉 and it adds native support for both 64-bit and ARM. Thank you for the issue @AlexanderDankin.
