### ISSUE TITLE
[BUG]: After applying Standard selection Phone Link is broken

### ISSUE THREAD

**Issue by sla-te** [undergroundwires/privacy.sexy#350]
### Description
After applying Standard selection Phone Link is broken (and even reverting "All"), does not fix it back. 
I can confirm it did work before. Specifically what does not work is the feature, that you can accept and make
calls via Phone Link on Windows (Messages and Apps still work).

### OS
Windows 11 Version 22H2 (OS Build 22621.3447)

### Reproduction steps
1. Setup [Phone Link](https://www.microsoft.com/en-us/windows/sync-across-your-devices) on a clean Windows 11 and assert, that you can use the "Calls" feature.
2. Apply the Standard set of scripts and reboot. Confirm that the Calls feature does not work anymore.
3. Revert the Standard (or All) selection, reboot and confirm that the Calls feature still does not work.

### Screenshots
![image](https://github.com/undergroundwires/privacy.sexy/assets/22568014/0705b706-2129-432a-b952-e418faefd06d)

### Additional information
Worth to mention, that I first had problems getting it to work, having applied the standard settings of [ShutUp10](https://www.oo-software.com/en/shutup10). After applying the "Undo all changes" action and a reboot, it worked perfectly (I also already tried running that again hoping it would revert the changes made by privacy.sexy but it didn't help). So my guess is that anything privacy.sexy does is somewhat not revertible and causes the breakage. Any hints regarding how to provide detailed error information when running Phone Link to pinpoint the root cause is highly appreciated because I kind of enjoyed using this feature.

I also already tried running the script provided by https://github.com/undergroundwires/privacy.sexy/issues/315#issuecomment-2009414512 but it also didn't fix it.

**Comment by undergroundwires** [comment]
Hi @sla-te, if I understand this correctly, you already reverted whole Standard selection but it still fails?

You can try reverting "Disable app access to Bluetooth devices".

**Comment by undergroundwires** [comment]
As you already reverted "Standard", this should have been caused by privacy.sexy but another software/configuration/hardware issue. Irreversible scripts are just cleanup scripts that would have no impact on what you're experiencing. You need to restart after reverting "Standard" as you already did it.

Reverting "All" should be safe. It can restore other settings set by other apps.

If you find out the reason (if there was a bug with reversion process), please inform back so we can fix it.

**Comment by undergroundwires** [comment]
It's hard to reproduce for me but someone else in the community can help. I do not have physical access to a Windows machine with Bluetooth access.

You're right, these scripts should all have revert codes as they're pretty straightforward to restore. I have some work on local branches that I haven't pushed yet, so my last comment is incorrect for the latest released version.

If you're confident that this is caused by privacy.sexy, the best troubleshooting way, going through all `recommend: standard` that does not have revert logic, and restore those. I'm adding revert codes slowly to the ones missing but it takes a lot of time while I have some other priorities. I'd merge a PR for it. The file to look at to find the diff: [windows.yaml](https://github.com/undergroundwires/privacy.sexy/blob/0.13.2/src/application/collections/windows.yaml).

I think deleting `HKLM\Software\Policies\Microsoft` registry subtree completely would revert most of these (but not all). On default OS state these keys do not exist, so it's safe to execute.

If we figure out this script, I'll document it remove it from Standard right away.

**Comment by undergroundwires** [comment]
Thank you @sla-te for the information. I'll document all of the "Disable app access" scripts. Document that this script breaks Phone Link in the title and move it to Strict pool. Hopefully all Standard scripts will be documented, reversible and non-breaking meanwhile still being as aggressive as possible regarding disabling privacy.

**Comment by undergroundwires** [comment]
Thank you @sla-te for the information. I'll document all of the "Disable app access" scripts. Document that this script breaks Phone Link in the title and move it to Strict pool. Hopefully all Standard scripts will be documented, reversible and non-breaking meanwhile still being as aggressive as possible regarding protecting privacy.

**Comment by undergroundwires** [comment]
[0.13.4](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.4) is just released 🎉. It improves app disabling to resolve this issue, some of the improvements include:

- It adds caution text for all scripts about potential impacts.
- Move disabling app access to notifications from 'Standard' to 'Strict'.
- Move disabling app access to phone calls from 'Standard' to 'Strict'.
- Add more documentation to scripts
- Improve code comments for better clarity on generated outputs.
- Resolve error display in revert codes due to incorrect use of `reg  delete` commands.
- Fix disabling app access to trusted devices disables access to account information, name and picture on older versions of Windows.
- Rename script names for consistency and clarity.

Please create new issues for further ideas/problems.
