### ISSUE TITLE
[BUG]: Error Running Script

### ISSUE THREAD

**Issue by giogio33** [undergroundwires/privacy.sexy#351]
I disabled all antivirus and protection. Ran also as Administrator. I also tried in safe mode with networking. 80GB free on the disk.
This image was cleaned with Tweaking.com. Seems to run perfectly. It has been just upgraded from Win10-20H2 to Win10 22H2.
The only issue this image seems to have is that I have a windows security update failing after all upgrades and chose not to longer upgrade. Microsoft.

### Description

I get Error Running Script, Fully Control on AppData\Roaming\privacy.sexy\runs and I tested it

### OS 

Win 10 Pro 22H2 (OS Build 19045.4355)

This image on 22H2 did not give me error prior upgrade to 22H2 from 20H2
I restored it to an image I had of the 20H2 prior running Privacy sexy, so it was clean

### Reproduction steps

I also tried to only select Clear recently Opened  application list and if gives error. This image on 22H2 did not give me error prior upgrade to 22H2

### Scripts

If applicable, please attach the generated privacy.sexy file instead of copy pasting which becomes too long.
[privacy-script.log](https://github.com/undergroundwires/privacy.sexy/files/15140077/privacy-script.log)

![2024-04-27 14_20_16-privacy sexy - Maximize Your Privacy and Security](https://github.com/undergroundwires/privacy.sexy/assets/168307664/dd4a1c72-4c62-4bae-b685-49b9ff15ec28)

### Additional information

[main.log](https://github.com/undergroundwires/privacy.sexy/files/15140075/main.log)

**Comment by undergroundwires** [comment]
Do you want to more context @giogio33 ?

**Comment by undergroundwires** [comment]
Hi @giogio33, thank you for all the context.

The logs show that:

1. Privacy.sexy is creating the script file, it's reading it back to trigger an antivirus to see if antivirus will delete it.
2. Privacy.sexy verifies that security scan was made possible and its not deleted.
3. It attempts to run the file, but can no longer find the file.

Some questions to understand whats going on:

1. Can you see any file at `AppData\Roaming\privacy.sexy\runs`? Which files do you see?
2. Do you run any other antivirus / security software other than Windows Defender?
3. Are you running Performance Mode [docs 1](https://learn.microsoft.com/en-us/defender-endpoint/microsoft-defender-endpoint-antivirus-performance-mode), [docs 2](https://www.bleepingcomputer.com/news/microsoft/microsoft-defender-antivirus-gets-performance-mode-for-dev-drives/) on Defender?
4. Can you try running after turning of [Real-Time protection](https://support.microsoft.com/en-us/windows/turn-off-defender-antivirus-protection-in-windows-security-99e6004f-c54c-8509-773c-a4d776b77960)?

**Comment by giogio33** [comment]
Thank you for your reply.

In the AppData\Roaming\privacy.sexy\runs I see all generated scripts batch files.

Performance Mode I read is for Windows11 and I have Win10-22H2. Is that correct then I don't have it?

I turned off Emsi-Antivirus Software and in windows security I get the following (screenshot) without rebooting and still privacysexy won't run. I may tray something deeper but I cannot for a couple of weeks. I'll get back to you with it. 
![2024-04-28 14_44_09-Windows Security](https://github.com/undergroundwires/privacy.sexy/assets/168307664/ca622502-c289-4e69-bffb-bbae5020ce84)

**Comment by undergroundwires** [comment]
Thank you for all of the information. It helped to eliminate other factors and I found out the problem.

privacy.sexy runs this files [using powershell](https://github.com/undergroundwires/privacy.sexy/blob/694bf1a74d935531d7cd46891823af1fa58c3c8c/src/infrastructure/CodeRunner/Execution/VisibleTerminalScriptFileExecutor.ts#L104-L110). 

It sends the script path in **double quotes** as argument to powershell [using double quotes](https://github.com/undergroundwires/privacy.sexy/blob/694bf1a74d935531d7cd46891823af1fa58c3c8c/src/infrastructure/CodeRunner/Execution/VisibleTerminalScriptFileExecutor.ts#L209-L214) to handle whitespaces in paths.

However for some reason, PowerShell strips away double quotes when it parses arguments, and fails when you have whitespace in script path (your user name in that case). See [StackOverflow thread](https://stackoverflow.com/questions/6714165/powershell-stripping-double-quotes-from-command-line-arguments) on this.

I set up a user with whitespace in its name and I can reproduce the issue.
I see that this can be resolved using double quotes + single quotes, double double quotes, using \" instead of double quotes etc etc.

I will solve this in next patch. Thank you again for the guidance and bug report.
