### ISSUE TITLE
0.13.3 DMG on Mac only contains the ARM64 version

### ISSUE THREAD

**Issue by mORogyrUly** [undergroundwires/privacy.sexy#362]
0.13.3 DMG on Mac only contains the ARM64 version - an Intel compiled version is unfortunately not included

**Comment by undergroundwires** [comment]
Thank you for @mORogyrUly. It is a bug, it was not intended. The bug is [explained here](https://github.com/undergroundwires/privacy.sexy/issues/348#issuecomment-2105742961). It was an unexpected side-effects of GitHub updating their runners.

I did a hot-patch now and updated 0.13.3 release to still be the Intel version, so it will be solved if you re-download the DMG file. I will fix this long-term in 0.13.4 with universal package support where both Intel and ARM binaries will be provided.

**Comment by undergroundwires** [comment]
[0.13.4](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.4) is just released  🎉 and it adds native support for both 64-bit and ARM. Thank you for the issue @mORogyrUly.
