### ISSUE TITLE
Privacy Cleanup Issue [Info]

### ISSUE THREAD

**Issue by dennyamarojr** [undergroundwires/privacy.sexy#37]
Hi @undergroundwires 

Recently I discover this amazing program and I'm loving, and I find some issue with the privacy cleanup and I fix the problem by searching in the famous google.com 

So the problem are in the Clear Windows Recent Files 

The original commands are:
echo --- Clear windows recent files
rd /s /q "%USERPROFILE%\Recent"
rd /s /q "%APPDATA%\Microsoft\Windows\Recent"
del /f /q %APPDATA%\Microsoft\Windows\Recent\AutomaticDestinations\*
del /f /q %APPDATA%\Microsoft\Windows\Recent\CustomDestinations\*

Everything is working perfectly and clear everything, but has one file in the AutomaticDestinations called f01b4d95cf55d32a.automaticDestinations-ms where is used by Quick Access.

My suggestion is add the command to create the folder and windows recover the file (at least windows are able to restore something by himself XD), so the correct command is:

echo --- Clear windows recent files
rd /s /q "%USERPROFILE%\Recent"
rd /s /q "%APPDATA%\Microsoft\Windows\Recent"
del /f /q %APPDATA%\Microsoft\Windows\Recent\AutomaticDestinations\*
del /f /q %APPDATA%\Microsoft\Windows\Recent\CustomDestinations\*
mkdir %AppData%\Microsoft\Windows\Recent\AutomaticDestinations

Now, Quick Access are back and everything working and cleared as we want 👍 

Source Link: https://www.winhelponline.com/blog/fix-quick-access-reset-pinned-shortcuts-stuck-not-working-windows-10/

**Comment by undergroundwires** [comment]
Hi @dennyamarojr , you're a community hero! The behavior was irritating me and some others I know as well but no one could detect the underlying issue. Thanks for finding that out and also suggesting a way to fix it.

I think we should remove following lines:

- `rd /s /q "%USERPROFILE%\Recent"`: folder does not exist for me?
- `rd /s /q "%APPDATA%\Microsoft\Windows\Recent"`: folder only contains `AutomaticDestinations` and `CustomDestinations` so no need to clear files here if we clear them.

I think we can also simply the rest of the scripts. I'm not sure why we're deleting `AutomaticDestinations*` and `CustomDestinations*`. There are only two folders with exact name of `AutomaticDestinations` and `CustomDestinations` without any text appended to them so we can just remove contents of those instead (remove to `*` wildcards).

Also maybe instead of deleting the folder and recreating them we can just delete their contents instead. So instead of `del /f /q folder` we can do  `del /f /q folder\*`. 

At last step I believe we should split this script into two. Then their purposes would be more clear to users then and we could have different recommendation options:

| Script name | Script | Recommend |
| --- | --- | --- |
| Clear recently accessed files |`del /f /q "%APPDATA%\Microsoft\Windows\Recent\AutomaticDestinations\*"` |`recommend: standard` |
| Clear user pins |`del /f /q "%APPDATA%\Microsoft\Windows\Recent\CustomDestinations\*"` | - (do not) |

I'm open to PR if you have time, otherwise I'll take a look at it. There are some improvements that I want to do in the queue then I'll prfioritize this one. Thanks again 🥂

**Comment by undergroundwires** [comment]
Hi @dennyamarojr , you're a community hero! The behavior was irritating me and some others I know as well but no one could detect the underlying issue. Thanks for finding that out and also suggesting a way to fix it, and happy to hear that you liked it ☺️

**1. Remove the lines**

I think we should remove following lines:

- `rd /s /q "%USERPROFILE%\Recent"`: folder does not exist for me?
- `rd /s /q "%APPDATA%\Microsoft\Windows\Recent"`: folder only contains `AutomaticDestinations` and `CustomDestinations` so no need to clear files here if we clear them.

**2. Remove the wildcards**

I think we can also simply the rest of the scripts. I'm not sure why we're deleting `AutomaticDestinations*` and `CustomDestinations*`. There are only two folders with exact name of `AutomaticDestinations` and `CustomDestinations` without any text appended to them so we can just remove contents of those instead (remove to `*` wildcards).

**3. Do not delete the folders**

Also maybe instead of deleting the folder and recreating them we can just delete their contents instead. So instead of `del /f /q folder` we can do  `del /f /q folder\*`. 

**4. Split the scripts and do not recommend deleting user pins**

At last step I believe we should split this script into two. Then their purposes would be more clear to users then and we could have different recommendation options:

| Script name | Script | Recommend |
| --- | --- | --- |
| Clear recently accessed files |`del /f /q "%APPDATA%\Microsoft\Windows\Recent\AutomaticDestinations\*"` |`recommend: standard` |
| Clear user pins |`del /f /q "%APPDATA%\Microsoft\Windows\Recent\CustomDestinations\*"` | - (do not) |

I'm open to PRs, otherwise I'll take a look at it. There are some improvements that I want to do in the queue then I'll prfioritize this one. Thanks again 🥂

**Comment by dennyamarojr** [comment]
> Hi @dennyamarojr , you're a community hero! The behavior was irritating me and some others I know as well but no one could detect the underlying issue. Thanks for finding that out and also suggesting a way to fix it, and happy to hear that you liked it ☺️
> 
> **1. Remove the lines**
> 
> I think we should remove following lines:
> 
> * `rd /s /q "%USERPROFILE%\Recent"`: folder does not exist for me?
> * `rd /s /q "%APPDATA%\Microsoft\Windows\Recent"`: folder only contains `AutomaticDestinations` and `CustomDestinations` so no need to clear files here if we clear them.
> 
> **2. Remove the wildcards**
> 
> I think we can also simply the rest of the scripts. I'm not sure why we're deleting `AutomaticDestinations*` and `CustomDestinations*`. There are only two folders with exact name of `AutomaticDestinations` and `CustomDestinations` without any text appended to them so we can just remove contents of those instead (remove to `*` wildcards).
> 
> **3. Do not delete the folders**
> 
> Also maybe instead of deleting the folder and recreating them we can just delete their contents instead. So instead of `del /f /q folder` we can do `del /f /q folder\*`.
> 
> **4. Split the scripts and do not recommend deleting user pins**
> 
> At last step I believe we should split this script into two. Then their purposes would be more clear to users then and we could have different recommendation options:
> 
> Script name	 Script	Recommend
> Clear recently accessed files	`del /f /q "%APPDATA%\Microsoft\Windows\Recent\AutomaticDestinations\*"`	`recommend: standard`
> Clear user pins	`del /f /q "%APPDATA%\Microsoft\Windows\Recent\CustomDestinations\*"`	- (do not)
> I'm open to PRs, otherwise I'll take a look at it. There are some improvements that I want to do in the queue then I'll prfioritize this one. Thanks again 🥂

Yeah Definitely has a lot more things to do, I'm noob on creating programs or even powershell scripts, and my computer I can't do too much test but I make my computer to the extreme. I discover a lot of tweaks and with privacy.sexy I discover more and also I'm working in a script to delete chromium browsers (temp files, cookies, caches and everything) so people don't need don't CCleaner or other program to delete those files. I will try to add them to the application.yaml and pull request 👍

**Comment by undergroundwires** [comment]
The fix is live in latest version [0.8.1](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.8.1)
