### ISSUE TITLE
[Bug]:  error running script 

### ISSUE THREAD

**Issue by fruitsaladchan** [undergroundwires/privacy.sexy#403]
### Description

Get an error when running the script . I have disabled windows defender and also ran as Admin. I've tried running it multiple times with different options and still get the same error

### How can the bug be recreated?

1. select options
2. run
3. get error

### Operating system

Windows 11 IoT Enterprise LTSC 24H2

### Script file

https://gist.github.com/fruitsaladchan/b533b44c5443db2bf1ab34b0d5203bc0

### Screenshots

![Screenshot (1)](https://github.com/user-attachments/assets/dd8a44d1-7f17-4240-a198-7d178594f75e)

### Additional information

[main.log](https://github.com/user-attachments/files/16488802/main.log)
[error.txt](https://github.com/user-attachments/files/16488804/error.txt)

**Comment by femdiya** [comment]
uhhh, I found this : https://github.com/Microsoft/vscode/issues/28271#issuecomment-308592929
which suggests that you need to ensure that the file exist, usually, it is caused by defender which blocks scripts automatically and doesn't inform the user, you may also wanna check "protection history" in defender.

You may can check #392 too.

**Comment by fruitsaladchan** [comment]
yea im pretty stupid idk how but my cmd.exe was missing

**Comment by femdiya** [comment]
I have sooo many questions...

**Comment by undergroundwires** [comment]
We should output specific error message if terminal (`cmd.exe`) or `PowerShell.exe` is missing. Very rare but this may happen. Thanks for reporting back the cause @fruitsaladchan.
