### ISSUE TITLE
Help needed to block CryptSvc and services.exe from establishing Internet connections

### ISSUE THREAD

**Issue by moctus** [undergroundwires/privacy.sexy#451]
In TCPView I can often see established TCP connections of CryptSvc and services.exe to IP addressess like 172.217.16.3, 23.74.173.42, 199.232.210.172, etc on port 80. I already created Windows Firewall rules and disabled the services by editing various entries in HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services but that did not help. I don't want to see those established connections anymore and don't want to install 3rd party software. Could you please help me?

**Comment by Marc05** [comment]
IMO this (firewall rule management) and hosts-file blocking are not worth the technical debt considering the issue is better solved by actual firewalls (e.g. Portmaster and simplewall). I do understand the demand for it though. On a more related note, I advise against blocking those since they provide important functionality.

**Comment by moctus** [comment]
I'm using simplewall. No more problems, thank you.
