### ISSUE TITLE
Uninstall feature/capability when disabling it.

### ISSUE THREAD

**Issue by Marc05** [undergroundwires/privacy.sexy#47]
Apparently, disabling a Windows feature does not uninstall/remove it from the system; e.g. Windows Media Player
https://www.tenforums.com/tutorials/95101-install-uninstall-windows-media-player-windows-10-a.html

> If you like, you can turn on or off the Windows Media Player feature to no longer have it available for all users on the PC. Turning off Windows Media Player will not uninstall it, or save any hard drive space.

This can be accomplished with the /Remove-Capability parameter for DISM.

````
Get-WindowsCapability -Online -Name "*assist*"


Name         : App.Support.QuickAssist~~~~0.0.1.0
State        : Installed
DisplayName  : Microsoft Quick Assist
Description  : Allows Microsoft support agents to connect to your device and also lets you share your screen with
               someone you trust so they can help you.
DownloadSize : 400810
InstallSize  : 3034496

Dism /Online /Remove-Capability /CapabilityName:App.Support.QuickAssist~~~~0.0.1.0

Deployment Image Servicing and Management tool
Version: 10.0.19041.329

Image Version: 10.0.19042.508

[==========================100.0%==========================]
The operation completed successfully.
````

**Comment by Marc05** [comment]
This should be implemented to all features that need it, but I don't have the setup to test each listed feature on the project.

**Comment by undergroundwires** [comment]
Hi @Marc05 , awesome to see you again and thanks for the suggestion.

I'm sorry but I don't really understand what we should do here. I just refactored those tweaks to call a single function so we can change the behavior [at one place on this line](https://github.com/undergroundwires/privacy.sexy/blob/c4ec6a1445d2fd5eb923c97b54aee01e272e13a8/src/application/application.yaml#L4061).

As you see on that line run a PowerShell command `Get-WindowsCapability -Online -Name '{{ $capabilityName }}*'' | Remove-WindowsCapability -Online` instead of `dism`. The reason we changed the behavior was that someone in the community pointed out that the versions (in your example it's `~~~~0.0.1.0`) change per installation so we run a `Get` to get the version that exists on the computer.

[According to the documentation](https://docs.microsoft.com/en-us/powershell/module/dism/remove-windowscapability?view=win10-ps#description) `Remove-WindowsCapability` will uninstall the capabilities. Is it not working as expected?

**Comment by Marc05** [comment]
Hmm, I don't remember why I thought it was only being removed and not uninstalled. Perhaps because the checkbox text made it sound that way? Either way, the new commit looks good to me.

**Comment by undergroundwires** [comment]
[0.8.2](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.8.2) is now live where I also renamed "disable" to "uninstall" to make it sound right way 😊. Feel free to re-open this if there's anything more we can do.

**Comment by barunintune** [comment]
What we can do if device not have internet connection. Like offline enablement
