### ISSUE TITLE
 I lost control

### ISSUE THREAD

**Issue by itady74** [undergroundwires/privacy.sexy#63]
After I used the script, accordantly lost the administration control from my device, and if I need to get my premises back I can't do it. So please if someone can help me just help me.

**Comment by undergroundwires** [comment]
Hi @itady74 , I'm sorry for that. Would you please provide more context so we can help you solve it?

- **Describe the bug**
  - A clear and concise description of what the bug is. 
- **OS**
  - Which OS are you using?
  - What version of OS you were using?
    - On Windows you can find it using "Start button" > "Settings" > "System" > "About".
    - On macOS you can find it using "Apple menu (top left corner)" > "About This Mac".
- **Screenshots**
  - If applicable, add screenshots to help explain your problem.
 - **Scripts**
   - Which scripts did you execute? If applicable, please paste the executed scripts or attach the generated privacy.sexy file
- **Additional information**
  - Add any other context about the problem here.

**Comment by itady74** [comment]
I fixed the problem yesterday with the revert features thank you

**Comment by undergroundwires** [comment]
Happy to hear that! We could document them better in future versions if you'd share which tweaks that caused the unexpected behavior

**Comment by itady74** [comment]
But I have another issue too, and I push it yesterday

**Comment by undergroundwires** [comment]
I've seen it and understand you're worried but please be patient. We have a small community trying to help each other in their free time.
