### ISSUE TITLE
Windows Spotlight stop working

### ISSUE THREAD

**Issue by Rohlik** [undergroundwires/privacy.sexy#65]
Hello and thank you so much for this project!
I generated and run script on my Win10 and Windows **Spotlight** stop working (random wallpaper on lock screen). Is there any chance to make it work again?
Thank you.

**Comment by undergroundwires** [comment]
Hi @Rohlik,

Windows Spotlight feature sends data to Microsoft servers and it's recommended to disable it (also often disabled in enterprise managed computers).

It's most likely the script called "Disable targeted tips" that has caused it. So it would work if you revert that using the following code:

```
reg add "HKLM\Software\Policies\Microsoft\Windows\CloudContent" /v "DisableWindowsSpotlightFeatures" /t "REG_DWORD" /d "0" /f
```

We should:
- Add revert option for the script (missing right now)
- Document it better, disabling spotlight should not be under "Disable targeted tips" (that's why I mark this as bug)

**Comment by undergroundwires** [comment]
Closing this as now the behavior is better documented
