### ISSUE TITLE
No permission to install applications

### ISSUE THREAD

**Issue by playgithub** [undergroundwires/privacy.sexy#85]
After applying some scripts, got some permission problems as below:
* When install applications not enough permission, error code: 2502, 2503
* Use `copy` to overwrite a file in `C:\Windows` in terminal with admin priviledge, but still no permission

Which script(s) cause the problems?
How to fix it? Or any workaround if better?

**Comment by undergroundwires** [comment]
*Some* is not a very good description for a bug. [This](https://testlio.com/blog/the-ideal-bug-report/) is a very good article about bug reporting. We need more context or it's very low likely that you'll get help from anyone in community. Would you feel the information asked in the [issue template](https://github.com/undergroundwires/privacy.sexy/issues/new/choose) for bug scripts?

**Comment by playgithub** [comment]
I can't reproduce it now.
I tried it again just now, it succeeded.

In terminal (admin), run
```
cp hh_fixed.exe C:\Windows\hh.exe
```
`hh.exe` is the native chm viewer by Microsoft.

I'll post it with steps for reproducing if  I can reproduce it.

Thanks

**Comment by NewKidOnTheBlock** [comment]
Here are reproduction steps:
- Download Calibre 7.0 from https://calibre-ebook.com/download_windows
- Try to install
- Encounter error codes 2502 and 2503

**Comment by undergroundwires** [comment]
Do you have the script you executed @NewKidOnTheBlock ?

I cannot inspect this further without having the script.

**Comment by undergroundwires** [comment]
Tested on Windows 11 22H2, Windows 11 22H1, Windows 10 22H2 and I still cannot reproduce this.

Steps I've taken:

1. Run `Remove associations of default apps`
2. Download Calibre 7.0 from https://calibre-ebook.com/download_windows

I tried also after restarting the machines but they still install successfully.

As second test I run all scripts inside "Privacy cleanup" and it could install Calibre.

This must be another script from another category. It would be nice if someone could share the full script file then I can see if running the same copy will result in same behavior and what's causing this. Version [0.12.6](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.6) improved safety of any kind of cleanup, so this may be solved naturally.

If the latest privacy.sexy does not cause this anymore, this could have been due to #145, #176 or #89 that are all fixed.

**Comment by NewKidOnTheBlock** [comment]
The .msi problem still persists.

**Comment by undergroundwires** [comment]
Maybe this is due to older privacy.sexy versions deleting `%WINDIR%\Temp` directly instead of it's contents. If you do not have it, creating a folder called "Temp" under `C:\Windows` would solve it. All deletion logic are now safer (just clearing contents, not directory itself) since [v0.12.6](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.6) but as you executed older versions, this may be the issue.

**Comment by undergroundwires** [comment]
Maybe this is due to older privacy.sexy versions deleting `%WINDIR%\Temp` directly instead of it's contents. If you do not have it, creating a folder called `Temp` under `C:\Windows` would solve it. All deletion logic are now safer (just clearing contents, not directory itself) since [v0.12.6](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.6) but as you executed older versions, this may be the issue.

**Comment by undergroundwires** [comment]
Or can it be due to removal of `Microsoft.DesktopAppInstaller`? In that case it should be documented, try reverting that.

**Comment by NewKidOnTheBlock** [comment]
Temp folder exists. That can't be the cause.
Which option is Microsoft.DesktopAppInstaller?

**Comment by undergroundwires** [comment]
![image](https://github.com/undergroundwires/privacy.sexy/assets/15555035/bb49c345-5994-498f-b943-5b539be1ccfa)

**Comment by NewKidOnTheBlock** [comment]
Thanks, created a revert script from that:
![skip](https://github.com/undergroundwires/privacy.sexy/assets/12411527/1161fa07-cfba-465c-9c99-65185ef7484d)

"Remove AppInstaller app is not part of the Standard set and hadn't been missing.

**Comment by NewKidOnTheBlock** [comment]
@playgithub
@kalekad 
I've found a solution!
The problem lies with the permissions of the `C:\Windows\Temp` folder.
Somehow Administrators -> _Full Control_ is not enough.

You need to add set <Current User> to _Full Control_ and that solves it.
.msi installers run smoothly now.
I've just tested it with Mumble and Calibre.
