### ISSUE TITLE
Cosmetic usability improvements

### ISSUE THREAD

**Issue by Kizaemon** [undergroundwires/privacy.sexy#88]
Thank you for your library of tweaks!

I noticed two minor usability issues, which could be improved.
This is the online version for windows, card layout.
I tried with Firefox and Opera.

1) Expand a card on the left side, and select an item (checkbox) inside of that card -- a script is generated at the right side.
Now when I select any characters in the generated script, the card is collapsing and I'm losing the context of what card/checkbox I selected last.

It would be great to keep the left side card expansion state unchanged, when navigating in the script.
The tree layout has not the problem of losing collapsing/losing context.

2) When copying few lines of the script to clipboard, the lines are separated with LF, not CRLF.
I need to fixup new lines breaks in an editor (Notepad++) before running the selected lines in command prompt.
I understand your intent is to download the script as a bat file, but I'd like to have an option to run selected lines only.

It would be great if the Windows version would use CRLF when copying to clipboard.

**Comment by undergroundwires** [comment]
Hi @Kizaemon , welcome to the community. Thank you for using it and your valuable feedback. Both suggestions will be implemented.

1. It was implemented for mobile users. I noticed that clicking on run/download buttons do the same which is intrusive. I'll redo the logic so instead of having exceptions for collapsing cards, cards will only be closed when clicking on outer background.

2. You're right, we need to address this. I see three options going forward:

a. Based on client OS: use LF for Unix-based systems and CRLF for Windows, regardless of bash/batch file
b. Based on language: Use CRLF for batch files, LF for bash, regardless of client OS
c. Always use CRLF regardless of platform. Seems to be simplest option. Is there any disadvantages to this?

How do you think we should go forward?

**Comment by undergroundwires** [comment]
Hi @Kizaemon , welcome to the community. Thank you for using it and your valuable feedback. Both suggestions will be implemented.

1. It was implemented for mobile users. I noticed that clicking on run/download buttons on bottom do the same which is intrusive. I'll fix both.

2. You're right, we need to address this. I see three options going forward:

a. Based on client OS: use LF for Unix-based systems and CRLF for Windows, regardless of bash/batch file
b. Based on language: Use CRLF for batch files, LF for bash, regardless of client OS
c. Always use CRLF regardless of platform. Seems to be simplest option. Is there any disadvantages to this?

How do you think we should go forward?

**Comment by undergroundwires** [comment]
Bash [does not seem to accept [CRLF](https://unix.stackexchange.com/a/577668), then generated batch files will be using CRLF and bash LF. So we'll go with option b.

@Kizaemon in your case you were having the issue with about copying from generated script files, not on the textbox on website/desktop app right?

**Comment by undergroundwires** [comment]
Released in [0.12.0](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.0)
